### ISSUE TITLE
Grinding error. Will not grind the wrong square

### ISSUE THREAD

**Issue by BlueSeaAndDragon** [SKO85/SE-Mods#5]
An error occurred. The nano machine will not grind the blocks that are different from the projection of the projector

**Comment by SKO85** [comment]
@BlueSeaAndDragon . Please provide details about the issue and if you have a video so I can reproduce it before I am able to fix it. I do not understand your reported issue at this moment.

**Comment by BlueSeaAndDragon** [comment]
@SKO85 The video cannot be sent out because it is too large, so I can only provide a link
【Space Engineers】 https://www.bilibili.com/video/BV1aH4y1u7Ay/?share_source=copy_web&amp;vd_source=dc92cbc32b93e94be9add023ab226107
Description: When the welding and grinding of the nanometer machine are normal, whether the color is selected or not, the "Build new" function fails to work




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SKO85/SE-Mods"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月20日(星期一) 晚上8:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SKO85/SE-Mods] Grinding error. Will not grind the wrong square (Issue #5)





 
@BlueSeaAndDragon . Please provide details about the issue and if you have a video so I can reproduce it before I am able to fix it. I do not understand your reported issue at this moment.

**Comment by SKO85** [comment]
Cannot reproduce.
